language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
deploy:
    provider: releases
    api_key: "5b228f8e9d399f819824d4ecc403f4acfe96642d"
    file:
    - "dist/angular-iod-client.js"
    - "dist/angular-iod-client.min.js"
    skip_cleanup: true
    on:
      tags: true
